name: playsound
description: Play Sound with Miniaudio
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  ffi: ^2.0.0
  miniaudio:
    path: ../miniaudio

dev_dependencies:
  lints: ^2.0.0
